[build]
  functions = "./functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run install-client && npm run build-client && npm install"
  targetPort = 5173
  port = 8888